// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8muJKzcC3v8mSv7Hh7an7JVLhqYrHm3Q',
    appId: '1:310745858069:web:a1361cb6d3203e03718e1c',
    messagingSenderId: '310745858069',
    projectId: 'learn-firestroe',
    authDomain: 'learn-firestroe.firebaseapp.com',
    storageBucket: 'learn-firestroe.appspot.com',
    measurementId: 'G-8V6LYSRYRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiNPDKYh1x9u7LBUaBdiZUBuOKuQpL7xE',
    appId: '1:310745858069:android:072c6b779c81f0e6718e1c',
    messagingSenderId: '310745858069',
    projectId: 'learn-firestroe',
    storageBucket: 'learn-firestroe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUAqf36UJ-PAUT_AIEfPt2mib51394bXc',
    appId: '1:310745858069:ios:325a4023c11968a1718e1c',
    messagingSenderId: '310745858069',
    projectId: 'learn-firestroe',
    storageBucket: 'learn-firestroe.appspot.com',
    iosBundleId: 'com.example.learnFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUAqf36UJ-PAUT_AIEfPt2mib51394bXc',
    appId: '1:310745858069:ios:325a4023c11968a1718e1c',
    messagingSenderId: '310745858069',
    projectId: 'learn-firestroe',
    storageBucket: 'learn-firestroe.appspot.com',
    iosBundleId: 'com.example.learnFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8muJKzcC3v8mSv7Hh7an7JVLhqYrHm3Q',
    appId: '1:310745858069:web:b70a6d74afc0a20f718e1c',
    messagingSenderId: '310745858069',
    projectId: 'learn-firestroe',
    authDomain: 'learn-firestroe.firebaseapp.com',
    storageBucket: 'learn-firestroe.appspot.com',
    measurementId: 'G-0SPNB4WS3Q',
  );
}
